# Generated by Django 5.2.15 on 2026-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0004_collaboration_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeblock",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "按类别"),
                    ("blue", "蓝色"),
                    ("purple", "紫色"),
                    ("green", "绿色"),
                    ("orange", "橙色"),
                    ("pink", "粉色"),
                    ("cyan", "青色"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="timeblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__in", ["", "blue", "purple", "green", "orange", "pink", "cyan"])),
                name="lab_valid_block_color",
            ),
        ),
    ]
