# Generated by Django 5.2.15 on 2026-10-08 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Category = apps.get_model("lab", "PersonalCategory")
    Item = apps.get_model("lab", "PersonalItem")
    Block = apps.get_model("lab", "TimeBlock")
    Audit = apps.get_model("lab", "Audit")
    defaults = (
        ("project", "项目任务", "#1d4ed8"),
        ("research", "科研", "#7c3aed"),
        ("study", "学习", "#15803d"),
        ("mentoring", "带教", "#c2410c"),
    )
    for workspace_id, user_id in Item.objects.values_list("workspace_id", "user_id").distinct():
        for position, (kind, name, color) in enumerate(defaults):
            category = Category.objects.create(
                workspace_id=workspace_id, user_id=user_id, name=name, color=color, position=position, legacy_key=kind
            )
            Item.objects.filter(workspace_id=workspace_id, user_id=user_id, kind=kind).update(category_id=category.id)
        Audit.objects.create(
            workspace_id_snapshot=workspace_id, actor_id=user_id, action="planning.categories_initialized"
        )
    for old, color in {
        "blue": "#1d4ed8",
        "purple": "#7c3aed",
        "green": "#15803d",
        "orange": "#c2410c",
        "pink": "#be185d",
        "cyan": "#0e7490",
    }.items():
        Block.objects.filter(color=old).update(color=color)
    # Flush deferred FK checks before PostgreSQL adds constraints in this transaction.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("lab", "0005_timeblock_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=7)),
                ("position", models.PositiveIntegerField(default=0)),
                ("legacy_key", models.CharField(blank=True, default="", max_length=16)),
            ],
            options={
                "ordering": ["position", "created_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="timeblock",
            name="lab_valid_block_color",
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="personalcategory",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="personalcategory",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.workspace"),
        ),
        migrations.AddField(
            model_name="personalitem",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="lab.personalcategory"
            ),
        ),
        migrations.RunPython(migrate_categories),
        migrations.AddConstraint(
            model_name="timeblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("color", ""), ("color__regex", "^#[0-9a-f]{6}$"), _connector="OR"),
                name="lab_valid_block_color",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalcategory",
            constraint=models.UniqueConstraint(fields=("workspace", "user", "name"), name="lab_category_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="personalcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__regex", "^#[0-9a-f]{6}$")), name="lab_category_valid_color"
            ),
        ),
    ]
