# Generated by Django 5.2.15 on 2026-10-08 20:00

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("lab", "0006_personal_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)),
                ("costs", models.DecimalField(decimal_places=2, max_digits=14)),
                ("D", models.DecimalField(decimal_places=2, max_digits=14)),
                ("source", models.TextField()),
                ("risk", models.DecimalField(decimal_places=2, max_digits=14)),
                ("execution", models.DecimalField(decimal_places=2, max_digits=14)),
                ("history", models.DecimalField(decimal_places=2, max_digits=14)),
                ("history_snapshot", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BountyPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True)),
                ("deliverable", models.TextField(blank=True)),
                ("criteria", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "bounty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="publication", to="lab.bounty"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BountyTaskAccess",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("requires_project_membership", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="task_access", to="lab.allocation"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinancePolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="db.workspace")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_id_snapshot", models.UUIDField(null=True)),
                ("kind", models.CharField(max_length=32)),
                ("scope_key", models.CharField(max_length=160, unique=True)),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.project"),
                ),
                ("stage", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="lab.stage")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db.workspace")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinancialOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_id_snapshot", models.UUIDField(null=True)),
                ("kind", models.CharField(max_length=40)),
                ("request_key", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("actor_name", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("evidence", models.TextField(blank=True)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.project"),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="lab.financialoperation",
                    ),
                ),
                ("stage", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="lab.stage")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delta", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="lab.financialaccount"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="lab.cashbatch"),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="lab.financialentry",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="lab.financialoperation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cashbatch",
            name="operation",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
        ),
        migrations.CreateModel(
            name="PaymentCommitment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="lab.financialaccount",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflinePayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)),
                ("withheld", models.DecimalField(decimal_places=2, max_digits=14)),
                ("net", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference", models.CharField(max_length=255)),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="lab.paymentcommitment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommitmentCancellation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
                (
                    "commitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation",
                        to="lab.paymentcommitment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RewardFormula",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_id_snapshot", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("task_expression", models.TextField()),
                ("member_expression", models.TextField()),
                ("parameters", models.JSONField(default=list)),
                ("reason", models.TextField()),
                ("actor_name", models.CharField(max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.project"),
                ),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="RewardForecast",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=12)),
                ("basis", models.CharField(max_length=12)),
                ("user_id_snapshot", models.UUIDField(null=True)),
                ("expression", models.TextField()),
                ("inputs", models.JSONField()),
                ("result", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_forecast_authors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("bounty", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="lab.bounty")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("formula", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lab.rewardformula")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RewardSettlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id_snapshot", models.UUIDField()),
                ("user_name", models.CharField(max_length=255)),
                ("kind", models.CharField(default="execution", max_length=12)),
                ("revision", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("performance_basis", models.TextField()),
                (
                    "forecast",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="lab.rewardforecast"),
                ),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentcommitment",
            name="settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="commitments", to="lab.rewardsettlement"
            ),
        ),
        migrations.CreateModel(
            name="StageBudget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("E", models.DecimalField(decimal_places=2, max_digits=14)),
                ("purposes", models.JSONField(default=list)),
                ("members", models.JSONField(default=list)),
                ("upgraded", models.BooleanField(default=False)),
                ("history", models.JSONField(default=list)),
                ("actor_name", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "stage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cash_budget", to="lab.stage"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rewardsettlement",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="settlements", to="lab.stagebudget"
            ),
        ),
        migrations.AddField(
            model_name="rewardforecast",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="forecasts", to="lab.stagebudget"
            ),
        ),
        migrations.AddField(
            model_name="cashbatch",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="lab.stagebudget"
            ),
        ),
        migrations.CreateModel(
            name="BountyMaterial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("document_version", "document_version"), ("attachment", "attachment")], max_length=24
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("document_snapshot", models.JSONField(default=dict)),
                ("attachment_key", models.CharField(blank=True, max_length=800)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "attachment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.fileasset"),
                ),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="lab.bounty"
                    ),
                ),
                (
                    "page_version",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.pageversion"),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("attachment__isnull", True), ("kind", "document_version")),
                            models.Q(("kind", "attachment"), ("page_version__isnull", True)),
                            _connector="OR",
                        ),
                        name="lab_bounty_material_kind",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="financialoperation",
            constraint=models.UniqueConstraint(fields=("workspace", "request_key"), name="lab_finance_request_unique"),
        ),
        migrations.AddConstraint(
            model_name="financialentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta", 0), _negated=True), name="lab_financial_entry_nonzero"
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross__gt", 0),
                    ("withheld__gte", 0),
                    ("net__gte", 0),
                    (
                        "gross",
                        django.db.models.expressions.CombinedExpression(models.F("net"), "+", models.F("withheld")),
                    ),
                ),
                name="lab_payment_valid_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardformula",
            constraint=models.UniqueConstraint(
                fields=("project_id_snapshot", "version"), name="lab_formula_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcommitment",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="lab_commitment_positive"),
        ),
        migrations.AddConstraint(
            model_name="stagebudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("E__gte", 0)), name="lab_stage_cash_budget_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardsettlement",
            constraint=models.UniqueConstraint(
                fields=("budget", "user_id_snapshot", "kind", "revision"), name="lab_settlement_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardsettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="lab_settlement_nonnegative"
            ),
        ),
    ]
