# Generated by Django 5.2.15 on 2026-10-08 20:13

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("lab", "0008_finance_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardforecast",
            name="actor_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="PublicDutyAward",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id_snapshot", models.UUIDField()),
                ("user_name", models.CharField(max_length=255)),
                ("period", models.CharField(max_length=7)),
                ("group_key", models.UUIDField(default=uuid.uuid4)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("duty", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="PublicDutyCommitment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_commitments",
                        to="lab.financialaccount",
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="lab.publicdutyaward",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicDutyPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)),
                ("withheld", models.DecimalField(decimal_places=2, max_digits=14)),
                ("net", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference", models.CharField(max_length=255)),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="lab.publicdutycommitment",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="lab.financialoperation"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="publicdutyaward",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="lab_public_duty_positive"),
        ),
        migrations.AddConstraint(
            model_name="publicdutyaward",
            constraint=models.UniqueConstraint(
                fields=("group_key", "revision"), name="lab_public_duty_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicdutycommitment",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="lab_public_commit_positive"),
        ),
        migrations.AddConstraint(
            model_name="publicdutypayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross__gt", 0),
                    ("withheld__gte", 0),
                    ("net__gte", 0),
                    (
                        "gross",
                        django.db.models.expressions.CombinedExpression(models.F("net"), "+", models.F("withheld")),
                    ),
                ),
                name="lab_public_payment_valid",
            ),
        ),
    ]
