# Generated by Django 5.2.15 on 2026-10-08 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("lab", "0010_public_duty_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="publicdutyaward",
            name="lab_public_duty_positive",
        ),
        migrations.AddConstraint(
            model_name="publicdutyaward",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="lab_public_duty_positive"),
        ),
    ]
