export type LabFinancePermission = "view" | "record" | "approve" | "pay";
export type LabFinancePermissionMembers = {
  project_id: string;
  members: { id: string; name: string; permissions: LabFinancePermission[]; owner: boolean }[];
};
/** Copyright (c) 2026 OpenOceanAcoustic and contributors. SPDX-License-Identifier: AGPL-3.0-only */
export type LabFormulaParameter = {
  name: string;
  scope: "task" | "member" | "stage";
  unit: string;
  source: string;
  default?: string;
};
export type LabRewardFormula = {
  id: string;
  project_id: string;
  version: number;
  task_expression: string;
  member_expression: string;
  parameters: LabFormulaParameter[];
  reason: string;
  actor: string;
  created_at: string;
};
export type LabRewardForecast = {
  id: string;
  stage_id: string;
  kind: "task" | "member";
  basis: "budget" | "received";
  bounty_id: string | null;
  user_id: string | null;
  actor?: string;
  project_id?: string;
  formula_id: string;
  formula_version: number;
  expression: string;
  inputs: Record<string, string>;
  result: string;
  created_at: string;
};
export type LabFinanceAccount = {
  id: string;
  project_id: string | null;
  stage_id: string | null;
  kind: string;
  label: string;
  balance: string;
  committed: string;
  available: string;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabFinanceMemberShare = { user_id: string; b: string; r: string; planned_vc: string };
export type LabFinanceHistoryShare = { user_id: string; share: string; qualified_at: string; basis: string };
export type LabFinanceStage = {
  id: string;
  stage_id: string;
  project_id: string;
  name: string;
  B: string;
  E: string;
  purposes: { name: string; amount: string }[];
  members: LabFinanceMemberShare[];
  upgraded: boolean;
  history: LabFinanceHistoryShare[];
  execution_funded: string | null;
  history_funded: string | null;
  formula_version: number | null;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
  deleted?: boolean;
  can_delete?: boolean;
  can_restore?: boolean;
  delete_reason?: string | null;
};
export type LabFinanceSettlement = {
  id: string;
  stage_id: string;
  user_id: string;
  user_name: string;
  kind: "execution" | "history";
  revision: number;
  amount: string;
  forecast_id: string | null;
  forecast_amount: string | null;
  difference: string | null;
  performance_basis: string;
  paid: string;
  withheld: string;
  net_paid: string;
  outstanding: string;
  committed: string;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabFinanceCommitment = {
  id: string;
  settlement_id: string;
  account_id: string;
  user_id: string;
  amount: string;
  paid: string;
  remaining: string;
  cancelled: boolean;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabFinancePayment = {
  id: string;
  commitment_id: string;
  settlement_id: string;
  user_id: string;
  gross: string;
  withheld: string;
  net: string;
  evidence: string;
  reference: string;
  created_at: string;
  occurred_at: string;
  reversed: boolean;
};
export type LabFinanceBatch = {
  id: string;
  operation_id?: string;
  kind?: "receipt" | "opening";
  stage_id: string;
  project_id: string;
  gross: string;
  costs: string;
  D: string;
  source: string;
  risk: string;
  execution: string;
  history: string;
  risk_released: string;
  risk_used?: string;
  risk_remaining: string;
  history_snapshot: LabFinanceHistoryShare[];
  created_at: string;
  occurred_at?: string;
  reversed?: boolean;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
  can_delete?: boolean;
  delete_reason?: string | null;
};
export type LabFinanceEntry = {
  id: string;
  operation_id: string;
  account_id: string;
  project_id: string | null;
  stage_id: string | null;
  kind: string;
  delta: string;
  reason: string;
  evidence: string;
  actor: string;
  created_at: string;
  occurred_at: string;
  reverses_id: string | null;
};
export type LabFinanceOperation = {
  id: string;
  kind: string;
  actor: string;
  reason: string;
  evidence: string;
  payload: Record<string, unknown>;
  created_at: string;
  occurred_at: string;
  reverses_id: string | null;
  reversed: boolean;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabFinanceOverview = {
  future_plan_limits?: Record<string, string>;
  manager_id: string | null;
  is_manager: boolean;
  allowed_actions?: string[];
  can_designate_manager?: boolean;
  public_summary?: { kind: string; label: string; balance: string; committed: string; available: string }[];
  projects: {
    id: string;
    name: string;
    is_lead: boolean;
    permissions?: LabFinancePermission[];
    allowed_actions?: string[];
    can_manage_permissions?: boolean;
    archived?: boolean;
    finance_deleted?: boolean;
    deleted?: boolean;
    can_manage?: boolean;
    can_delete?: boolean;
    can_restore?: boolean;
    delete_reason?: string | null;
  }[];
  members: { id: string; name: string; is_admin?: boolean }[];
  public_awards?: LabPublicDutyAward[];
  public_commitments?: LabPublicDutyCommitment[];
  public_payments?: LabPublicDutyPayment[];
  funding_targets?: { stage_id: string; project_id: string; project: string; name: string; E: string }[];
  accounts: LabFinanceAccount[];
  stages: LabFinanceStage[];
  formulas: LabRewardFormula[];
  forecasts: LabRewardForecast[];
  batches: LabFinanceBatch[];
  settlements: LabFinanceSettlement[];
  commitments: LabFinanceCommitment[];
  payments: LabFinancePayment[];
  operations: LabFinanceOperation[];
  entries: LabFinanceEntry[];
};
export type LabRecordWorkflowAction = {
  id: string;
  action: string;
  label: string;
  node_id: string;
  body: Record<string, string>;
  enabled: boolean;
  reason: string;
};
export type LabRecordWorkflow = {
  scope: "project" | "finance";
  project_id: string | null;
  title: string;
  active_node_ids: string[];
  nodes: { id: string; label: string; x: number; y: number; state: "current" | "completed" | "upcoming" }[];
  edges: { id: string; source: string; target: string }[];
  history: {
    id: string;
    label: string;
    node_id: string;
    actor: string;
    created_at: string;
    reason: string;
    source: { path: string; label: string } | null;
    occurred_at?: string;
    evidence?: string;
    snapshot?: Record<string, unknown>;
  }[];
  actions: LabRecordWorkflowAction[];
};

export type LabPublicDutyAward = {
  id: string;
  group_key: string;
  revision: number;
  user_id: string;
  user_name: string;
  period: string;
  duty: string;
  amount: string;
  paid: string;
  outstanding: string;
  committed: string;
  withheld: string;
  net_paid: string;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabPublicDutyCommitment = {
  id: string;
  award_id: string;
  user_id: string;
  user_name: string;
  account_id: string;
  amount: string;
  paid: string;
  remaining: string;
  cancelled: boolean;
  can_manage: boolean;
  can_pay?: boolean;
  can_approve?: boolean;
  can_record?: boolean;
};
export type LabPublicDutyPayment = {
  id: string;
  commitment_id: string;
  award_id: string;
  user_id: string;
  gross: string;
  withheld: string;
  net: string;
  evidence: string;
  reference: string;
  created_at: string;
  occurred_at: string;
  reversed: boolean;
};

export type LabStageAllocationRequest = {
  request_key: string;
  from_account_id: string;
  stage_id: string;
  amount: string;
  reason: string;
  evidence?: string;
  occurred_at?: string;
};
